### ISSUE TITLE
warn Plugin gatsby-plugin-intl is not compatible with your gatsby version 3.0.2 - It requires gatsby@^2.0.0  Is it possible to make it compatible with gatsby 3?

### ISSUE THREAD

**Issue by AleC77** [krashnamusika/krashna-site#58]
warn Plugin gatsby-plugin-intl is not compatible with your gatsby version 3.0.2 - It requires gatsby@^2.0.0

How do you think to resolve this issue?

I have also noticed that with Gatsby 3, gatsby-plugin-sitemap fails as conseguence.

**Comment by MathiasMeuleman** [comment]
Please file an issue with gatsby-plugin-intl, there is nothing we can help you with here.
